import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import SideBar from "@/components/SideBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Youtube Downloader",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <SidebarProvider>

          <main className="flex-1 flex flex-col items-center justify-center p-4 overflow-y-auto mt-20">

            <SideBar  />

            <SidebarTrigger className="fixed top-4 left-4 z-50 p-2 rounded-full bg-blue-600 text-white shadow-lg hover:bg-blue-700 transition duration-200">
              ☰
            </SidebarTrigger>
            {children}


          </main>
  
  
        </SidebarProvider>
     
      </body>
    </html>
  );
}
